# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'EmojiTransmitter' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmojiTransmitter
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3'
  pod 'SwiftyJSON', '~> 4.0'
end
